# Generated by Django 5.1 on 2024-10-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_alter_release_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ('version_name',), 'permissions': [('can_edit_is_active', 'can edit is active'), ('can_edit_version', 'can edit version')], 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
    ]
