# Generated by Django 5.1 on 2024-10-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_release_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ('version_name',), 'permissions': [('can_edit_is_active', 'can edit is active')], 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
    ]
